development:
  adapter: mysql2
  database: footprints
  username: root
  password: sel12345
  host: localhost
  port: 9393

local:
  adapter: mysql2
  database: footprints
  username: root
  password: sel12345
  host: localhost
  port: 9393

test:
  adapter: mysql2
  database: footprints_test
  username: root
  password: sel12345
  host: localhost
  port: 9393