default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: footprints
  password: sel12345

development:
  <<: *default
  host: localhost
  database: footprints_dev

test:
  <<: *default
  database: footprints_test

  production:
  <<: *default
  database: footprints